# Generated by Django 5.1 on 2026-01-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260120_0407'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(help_text='Username for login', max_length=150, unique=True),
        ),
    ]
