# Generated by Django 5.1 on 2025-12-25 18:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="User's full name (e.g., 'Emmanuel Cooper')", max_length=100)),
                ('code', models.CharField(help_text="Exactly 4 alphanumeric characters (e.g., 'EC21', 'AB12')", max_length=4, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be exactly 4 alphanumeric characters (A-Z, 0-9).', regex='^[A-Z0-9]{4}$')])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive users cannot access premium content')),
            ],
            options={
                'verbose_name': 'Premium User',
                'verbose_name_plural': 'Premium Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'code'], name='premium_use_name_75f846_idx'), models.Index(fields=['is_active'], name='premium_use_is_acti_789fb7_idx')],
                'unique_together': {('name', 'code')},
            },
        ),
    ]
