# Generated by Django 5.1 on 2026-01-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_users', '0001_initial'),
        ('scan', '0005_alter_airefine_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text="User's department - filters courses and topics", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_users', to='scan.department'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['department'], name='premium_use_departm_25a99c_idx'),
        ),
    ]
