# Generated by Django 5.1 on 2026-01-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('premium_users', '0001_initial'),
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='department',
            field=models.ForeignKey(blank=True, help_text="User's department - filters courses and topics", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_users', to='scan.department'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['name', 'code'], name='premium_use_name_75f846_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['is_active'], name='premium_use_is_acti_789fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumuser',
            index=models.Index(fields=['department'], name='premium_use_departm_25a99c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='premiumuser',
            unique_together={('name', 'code')},
        ),
    ]
