# Generated by Django 5.1 on 2026-01-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_users', '0002_premiumuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
