# Generated by Django 5.1 on 2026-01-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_users', '0003_alter_premiumuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
