# Generated by Django 5.1 on 2025-12-03 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_paths', models.JSONField(default=list)),
                ('pages_count', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('key_points', models.TextField(blank=True)),
                ('questions', models.TextField(blank=True)),
                ('answers', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai', to='scan.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('ai_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.aioutput')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
