# Generated by Django 5.1 on 2025-12-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_users', '0001_initial'),
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='If True, only selected premium users can access this topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='premium_users',
            field=models.ManyToManyField(blank=True, help_text='Select users who can access this premium topic', limit_choices_to={'is_active': True}, related_name='accessible_topics', to='premium_users.premiumuser'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_premium'], name='scan_topic_is_prem_19e3fa_idx'),
        ),
    ]
