# Generated by Django 5.1 on 2025-12-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_users', '0001_initial'),
        ('scan', '0002_topic_is_premium_topic_premium_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_deleted'], name='scan_topic_is_dele_642f9b_idx'),
        ),
    ]
