# Generated by Django 5.1 on 2025-12-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_users', '0001_initial'),
        ('scan', '0003_course_is_deleted_topic_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy - Quick Recognition'), ('medium', 'Medium - Understanding'), ('difficult', 'Difficult - Mastery')], default='medium', help_text='Determines explanation depth and context richness', max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='premium_users',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='accessible_topics', to='premium_users.premiumuser'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['difficulty_level'], name='scan_topic_difficu_083e5d_idx'),
        ),
    ]
