# Generated by Django 5.1 on 2025-12-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_users', '0001_initial'),
        ('scan', '0004_topic_difficulty_level_alter_topic_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airefine',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='airefine',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('difficult', 'Difficult')], default='medium', help_text='Difficulty level used when generating this refinement', max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy - Quick Recognition'), ('medium', 'Medium - Understanding'), ('difficult', 'Difficult - Mastery')], default='medium', help_text='Determines explanation depth and context richness for AI generation', max_length=20),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='If True, only selected premium users can access this topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='premium_users',
            field=models.ManyToManyField(blank=True, help_text='Select users who can access this premium topic', limit_choices_to={'is_active': True}, related_name='accessible_topics', to='premium_users.premiumuser'),
        ),
        migrations.AlterUniqueTogether(
            name='airefine',
            unique_together={('topic', 'provider', 'difficulty_level')},
        ),
    ]
