# Generated by Django 5.1 on 2026-01-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_alter_airefine_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airefine',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
